---
# =====================================================================
# roles/core/tasks/main.yml
#
# Purpose:
#   The core role provides foundational tools like os_loader and probes.
#   Executing this role directly initializes global environment facts.
# =====================================================================

- ansible.builtin.include_tasks: "sudo_loader.yml"
- ansible.builtin.include_tasks: "runtime_probe.yml"
