---
# =====================================================================
# roles/init/defaults/main.yml
# =====================================================================

# ---------------------------------------------------------------------
# Base Features
# ---------------------------------------------------------------------
init_mirror_enabled: false

# ---------------------------------------------------------------------
# User Configuration
# ---------------------------------------------------------------------
init_user_name: "ansible"
# init_user_password: "$6$..." # Optional

# -----------------------------------------------------d d d d d d----------------
# SSH Configuration
# ---------------------------------------------------------------------
init_sshd_port: 22
init_sshd_permit_root_login: "no"
init_sshd_password_authentication: "yes"
