---
# =====================================================================
# roles/init/vars/freebsd.yml
# =====================================================================

# OpenSSH
init_openssh_packages:
  - "openssh-portable"
init_sshd_service: "sshd"
