---
# =====================================================================
# roles/init/vars/openwrt.yml
# =====================================================================

# OpenSSH (OpenWrt uses Dropbear by default, but if openssh is needed)
init_openssh_packages:
  - "openssh-server"
init_sshd_service: "sshd"
