---
# =====================================================================
# roles/init/vars/suse.yml
# =====================================================================

# OpenSSH
init_openssh_packages:
  - "openssh"
init_sshd_service: "sshd"
