---
# =====================================================================
# roles/init/handlers/main.yml
# =====================================================================

- name: restart_sshd
  ansible.builtin.service:
    name: "{{ init_sshd_service | default('sshd', true) }}"
    state: restarted
  become: "{{ become_enabled }}"
  when: "ansible_virtualization_type | default('') != 'docker'"
