---
- name: Native Init Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Load infrastructure context
      ansible.builtin.include_role:
        name: context

    - name: Load base OS initialization
      ansible.builtin.include_role:
        name: init
