---
  - openssh
base_dev_packages: []
foundation_packages:
  - age
  - aria2
  - bash-completion
  - bat
  - bind-tools
  - busybox-suid
  - bzip2
  - ca-certificates
  - curl
  - fd
  - file
  - fzf
  - git
  - git-lfs
  - gnupg
  - gron
  - gzip
  - htop
  - httpie
  - inotify-tools
  - ipcalc
  - iperf3
  - iputils
  - jq
  - libcap
  - lsb-release
  - lsof
  - make
  - man-db
  - man-pages
  - moreutils
  - mtr
  - musl-locales
  - musl-locales-lang
  - ncdu
  - net-tools
  - netcat-openbsd
  - nmap
  - openssl
  - p7zip
  - parallel
  - patch
  - pinentry
  - pinentry-tty
  - procps-ng
  - psmisc
  - pv
  - ripgrep
  - rsync
  - shellcheck
  - socat
  - strace
  - stress-ng
  - sudo
  - sysstat
  - tcpdump
  - tig
  - tmux
  - tree
  - tzdata
  - unzip
  - vim
  - wget
  - xz
  - yq
  - zip
  - zstd
