---
base_dev_packages: []
foundation_packages:
  - bash-completion
  - bind-utils
  - bzip2
  - ca-certificates
  - curl-minimal
  - file
  - git
  - git-lfs
  - gnupg2-minimal
  - gzip
  - ipcalc
  - iperf3
  - iputils
  - jq
  - libcap
  - lsof
  - make
  - man-db
  - mtr
  - net-tools
  - nmap-ncat
  - openssl
  - patch
  - pinentry-curses
  - procps-ng
  - psmisc
  - rsync
  - socat
  - strace
  - sudo
  - tcpdump
  - tzdata
  - unzip
  - vim-enhanced
  - wget
  - xz
  - zip
  - zstd
