---
foundation_packages:
  - aria2
  - bat
  - bzip2
  - coreutils
  - curl
  - diffutils
  - fd
  - file
  - findutils
  - fzf
  - gawk
  - git
  - grep
  - gzip
  - htop
  - ipcalc
  - iperf3
  - jq
  - mtr
  - openssh
  - openssl
  - p7zip
  - parallel
  - pinentry-mac
  - pstree
  - ripgrep
  - rsync
  - socat
  - tcpdump
  - tmux
  - trash
  - tree
  - unzip
  - vim
  - wget
  - xz
  - zip
  - zstd
  - {{
