---
base_dev_packages: []
foundation_packages:
  - age
  - bash-completion
  - bat
  - bind-utils
  - bzip2
  - ca-certificates
  - fd-find
  - file
  - fzf
  - git
  - git-lfs
  - gnupg2
  - gzip
  - inotify-tools
  - ipcalc
  - iperf3
  - iputils
  - jq
  - libcap
  - lsb-release
  - lsof
  - make
  - man-db
  - mtr
  - ncdu
  - net-tools
  - nmap-ncat
  - openssl
  - p7zip
  - parallel
  - patch
  - pinentry-curses
  - procps-ng
  - psmisc
  - pv
  - ripgrep
  - rsync
  - shellcheck
  - socat
  - strace
  - sudo
  - tcpdump
  - tig
  - tzdata
  - unzip
  - vim-enhanced
  - wget
  - xz
  - yq
  - zip
  - zstd
